import 'package:fiap_hackathon/core/design_system/model/app_colors.dart';
import 'package:fiap_hackathon/core/design_system/tokens/colors.dart';

enum ColorThemeType { standard, highContrast, extremeContrast }

final colorThemes = {
  ColorThemeType.standard: AppColors(
    background: BaseColors.neutral0,
    backgroundFeedbackInfo: BaseColors.blue0,
    backgroundFeedbackSuccess: BaseColors.green0,
    backgroundFeedbackWarning: BaseColors.orange0,
    backgroundFeedbackDanger: BaseColors.red0,
    surface: BaseColors.neutral100,
    surfaceDisabled: BaseColors.neutral200,
    textPrimary: BaseColors.neutral700,
    textSecondary: BaseColors.neutral500,
    textDisabled: BaseColors.neutral400,
    textFeedbackInfo: BaseColors.blue300,
    textFeedbackSuccess: BaseColors.green100,
    textFeedbackWarning: BaseColors.orange100,
    textFeedbackDanger: BaseColors.red100,
    buttonPrimary: BaseColors.blue300,
    buttonSecondary: BaseColors.blue200,
    buttonDisabled: BaseColors.neutral400,
    border: BaseColors.blue300,
    borderDisabled: BaseColors.neutral400,
  ),

  ColorThemeType.highContrast: AppColors(
    background: BaseColors.blue700,
    backgroundFeedbackInfo: BaseColors.blue300,
    backgroundFeedbackSuccess: BaseColors.green100,
    backgroundFeedbackWarning: BaseColors.orange100,
    backgroundFeedbackDanger: BaseColors.red100,
    surface: BaseColors.blue500,
    surfaceDisabled: BaseColors.blue200,
    textPrimary: BaseColors.neutral0,
    textSecondary: BaseColors.neutral200,
    textDisabled: BaseColors.neutral300,
    textFeedbackInfo: BaseColors.blue300,
    textFeedbackSuccess: BaseColors.green100,
    textFeedbackWarning: BaseColors.orange100,
    textFeedbackDanger: BaseColors.red100,
    buttonPrimary: BaseColors.neutral0,
    buttonSecondary: BaseColors.blue100,
    buttonDisabled: BaseColors.neutral400,
    border: BaseColors.neutral0,
    borderDisabled: BaseColors.neutral300,
  ),

  ColorThemeType.extremeContrast: AppColors(
    background: BaseColors.neutral700,
    backgroundFeedbackInfo: BaseColors.neutral700,
    backgroundFeedbackSuccess: BaseColors.neutral700,
    backgroundFeedbackWarning: BaseColors.neutral700,
    backgroundFeedbackDanger: BaseColors.neutral700,
    surface: BaseColors.neutral700,
    surfaceDisabled: BaseColors.neutral700,
    textPrimary: BaseColors.yellow0,
    textSecondary: BaseColors.yellow100,
    textDisabled: BaseColors.yellow100,
    textFeedbackInfo: BaseColors.yellow0,
    textFeedbackSuccess: BaseColors.yellow0,
    textFeedbackWarning: BaseColors.yellow0,
    textFeedbackDanger: BaseColors.yellow0,
    buttonPrimary: BaseColors.neutral700,
    buttonSecondary: BaseColors.yellow0,
    buttonDisabled: BaseColors.yellow100,
    border: BaseColors.yellow0,
    borderDisabled: BaseColors.yellow100,
  ),
};
