import 'package:fiap_hackathon/core/design_system/model/app_colors.dart';
import 'package:fiap_hackathon/core/design_system/tokens/colors.dart';

enum ColorThemeType { standard, highContrast, extremeContrast }

final colorThemes = {
  ColorThemeType.standard: AppColors(
    background: BaseColors.neutral200,
    feedbackInfoLight: BaseColors.blue0,
    feedbackSuccessLight: BaseColors.green0,
    feedbackWarningLight: BaseColors.orange0,
    feedbackDangerLight: BaseColors.red0,
    surface: BaseColors.neutral0,
    textPrimary: BaseColors.neutral700,
    textSecondary: BaseColors.neutral500,
    textDisabled: BaseColors.neutral400,
    textInverse: BaseColors.neutral0,
    feedbackInfo: BaseColors.blue300,
    feedbackSuccess: BaseColors.green100,
    feedbackWarning: BaseColors.orange100,
    feedbackDanger: BaseColors.red100,
    primary: BaseColors.blue300,
    primaryInverse: BaseColors.neutral0,
    secondary: BaseColors.blue100,
    secondaryInverse: BaseColors.blue800,
    disabled: BaseColors.neutral400,
  ),

  ColorThemeType.highContrast: AppColors(
    background: BaseColors.blue700,
    feedbackInfoLight: BaseColors.blue300,
    feedbackSuccessLight: BaseColors.green0,
    feedbackWarningLight: BaseColors.orange0,
    feedbackDangerLight: BaseColors.red0,
    surface: BaseColors.blue500,
    textPrimary: BaseColors.neutral0,
    textSecondary: BaseColors.blue700,
    textDisabled: BaseColors.neutral300,
    textInverse: BaseColors.blue700,
    feedbackInfo: BaseColors.blue300,
    feedbackSuccess: BaseColors.green100,
    feedbackWarning: BaseColors.orange100,
    feedbackDanger: BaseColors.red100,
    primary: BaseColors.neutral0,
    primaryInverse: BaseColors.neutral700,
    secondary: BaseColors.blue100,
    secondaryInverse: BaseColors.neutral700,
    disabled: BaseColors.neutral400,
  ),

  ColorThemeType.extremeContrast: AppColors(
    background: BaseColors.neutral700,
    feedbackInfoLight: BaseColors.neutral700,
    feedbackSuccessLight: BaseColors.neutral700,
    feedbackWarningLight: BaseColors.neutral700,
    feedbackDangerLight: BaseColors.neutral700,
    surface: BaseColors.neutral600,
    textPrimary: BaseColors.yellow0,
    textSecondary: BaseColors.neutral0,
    textDisabled: BaseColors.neutral300,
    textInverse: BaseColors.neutral700,
    feedbackInfo: BaseColors.yellow0,
    feedbackSuccess: BaseColors.yellow0,
    feedbackWarning: BaseColors.yellow0,
    feedbackDanger: BaseColors.yellow0,
    primary: BaseColors.yellow0,
    primaryInverse: BaseColors.neutral700,
    secondary: BaseColors.neutral0,
    secondaryInverse: BaseColors.neutral700,
    disabled: BaseColors.neutral300,
  ),
};
